### PR TITLE
add tenant country

### PR DESCRIPTION
**Pull request by sduthil**

### CODE REVIEW

**Comment by fblackburn1** [comment]
If you add relationship to tenant table, you may want to add it to the [user loading strategy](https://github.com/wazo-platform/xivo-dao/blob/master/xivo_dao/resources/user/strategy.py)

**Comment by sduthil** [comment]
> If you add relationship to tenant table to expose new attribute, you may want to add it to the [user loading strategy](https://github.com/wazo-platform/xivo-dao/blob/master/xivo_dao/resources/user/strategy.py)

Good point. I was trying to add an automated test for this, but I can't find any difference in DB queries between the `unpaginated` strategy and `no` strategy... I'll need a bit of help on that one

**Review by DrPyser — APPROVED** [review]
All good

**Review by DrPyser — APPROVED** [review]
all good with joinedload strategy added

**Pull request merged**
