### PR TITLE
WP-697: fix huge query memory not released

### PR DESCRIPTION
**Pull request by ja0x**
TL;DR: joinedload creates too many cartesian products joins (huge table) with user's table because of the numerous relationships.  selectinload is a better strategy here because it avoids this problem by only joining with the tables PK at the cost of an one extra SQL statement being emitted

from sqla documentation:
```
Using multiple levels of depth with selectin loading does not incur the “cartesian” issue that joined and subquery eager loading have; the queries for selectin loading have the best performance characteristics and the fewest number of rows. The only caveat is that there might be more than one SELECT emitted depending on the size of the lead result.
```

### CODE REVIEW

**Comment by chartrandf** [comment]
Just curious, did we also have this memory issue when using the `/users?view=summary` query?

**Comment by ja0x** [comment]
> Just curious, did we also have this memory issue when using the `/users?view=summary` query?

Not that I could test, since most of the relationships are not loaded when using `summary` or `directory` view.  Did you notice any memory issues?

**Comment by chartrandf** [comment]
> > Just curious, did we also have this memory issue when using the `/users?view=summary` query?
> 
> Not that I could test, since most of the relationships are not loaded when using `summary` or `directory` view. Did you notice any memory issues?

We have a mention in WP-780, but we don't have a repeatable scenario. So not sure if really related to default view.

**Comment by sduthil** [comment]
Shouldn't we replace all occurrences of `joinedload` in all the codebase to avoid that kind of symptom in other scenarios than listing users?

**Comment by ja0x** [comment]
Not necessarily, there are still scenarios where it's preferable to use `joinedload`, `selectinload` still does perform an extra SQL query compared to `joinedload` and an extra every 500 collection instances returned.  So it's a balance between number of queries vs memory/performance when eagerloading is needed.  

from SQLA: ```joined eager loading only makes sense when the size of the collections are relatively small.```

But in general, I believe some queries would benefit from using `selectinload`, specially large queries and/or lots of relationship, while some others not so much.  Some additional testing would be required to find the best strategy for each

**Review by sduthil — APPROVED** [review]

**Pull request merged**
