### PR TITLE
incall: always set dialaction event/category/linked

### PR DESCRIPTION
**Pull request by sileht**
## incall: always set dialaction event/category/linked

### CODE REVIEW

**Comment by sileht** [comment]
> We need to talk about the behavior we want, we should stop fixing fixing thing without the whole picture...
> The actual behavior is a non-sense from rest-api point of view, we need to refactor the `linked` thing, not quickly monkey patch with causing other issues ...

Depending on the destination, I have seen different behavior, ivr/queue put linked=0 when deleted. But for device, you can't delete it if you have not dissociate it before. This is what you're talking about ?

**Comment by sileht** [comment]
I wasn't wondering why don't we just set the destination to type='none' by default when destination does exists anymore ?

**Comment by fblackburn1** [comment]
> I wasn't wondering why don't we just set the destination to type='none' by default when destination does not exists anymore ?

This is exactly what I'm talking about. The administrator would keep information on which destination its DID was set. So a system to keep destination information but disabling destination has been added .... :nauseated_face: 
And maybe there are other motivation that I don't know ...
We need to know if we still want this kind of behavior, but it's a decision from the PO

**Comment by fblackburn1** [comment]
IMO we should just remove dialaction when the resource is deleted. But we need to act carefully, since dialaction are used in a lot of resources and we must be clear with the impact

**Comment by sileht** [comment]
Maybe we can merge it ? I don't think changing the behavior of all destinations can be part of WAZO-163 due to the task priority.

**Comment by fblackburn1** [comment]
No this fix is wrong and we need to discuss about this kind of ticket
I just don't want to waste our time

**Pull request closed without merging**
