### PR TITLE
Remove Python 2 build and deps

### PR DESCRIPTION
**Pull request by sopelj**
Depends-on: wazo-platform/xivo-lib-python#113

### CODE REVIEW

**Review by fblackburn1 — APPROVED** [review]
We still have technical debt from python2 in `xivo_dao/helpers/db_views.py`
Since it may be out of scope of this ticket, please create JIRA ticket, then
* add it to your sprint
Or
* notify @ja0x if he want to make changes

**Comment by sopelj** [comment]
> xivo_dao/helpers/db_views.py

Oh ok. Do you mean the `columns = selectable.columns  # SQLAlchemy 1.2 compat` or is there more? If it's just that I can do it, if not perhaps a ticket would be better since I am less familiar with sqlalchemy and the potential workarounds that had been done.

**Comment by fblackburn1** [comment]
> > xivo_dao/helpers/db_views.py
> 
> Oh ok. Do you mean the `columns = selectable.columns # SQLAlchemy 1.2 compat` or is there more? If it's just that I can do it, if not perhaps a ticket would be better since I am less familiar with sqlalchemy and the potential workarounds that had been done.

I'm talking about mostly the whole implementation (except if the comment is false :man_shrugging: )
https://github.com/wazo-platform/xivo-dao/blob/master/xivo_dao/helpers/db_views.py#L23-L26

**Comment by sopelj** [comment]
> > > xivo_dao/helpers/db_views.py
> > 
> > 
> > Oh ok. Do you mean the `columns = selectable.columns # SQLAlchemy 1.2 compat` or is there more? If it's just that I can do it, if not perhaps a ticket would be better since I am less familiar with sqlalchemy and the potential workarounds that had been done.
> 
> I'm talking about mostly the whole implementation (except if the comment is false man_shrugging ) https://github.com/wazo-platform/xivo-dao/blob/master/xivo_dao/helpers/db_views.py#L23-L26

Oh wow. Ok. I'll make an issue because it would be good to do, but probably is out of scope of this specific PR.

**Comment by sopelj** [comment]
regate

**Pull request merged**
